include:
  - board: seeeduino_xiao_ble
    shield: SpaceBall
  - board: seeeduino_xiao_ble
    shield: settings_reset

on: [workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
